### ISSUE TITLE
One of your dependencies may have a security vulnerability (Jinja2 < 2.10.1)

### ISSUE THREAD

**Issue by zeroepoch** [NVIDIA/tensorrt-laboratory#25]
_Copied from internal bug tracking_

Known high severity security vulnerability detected in Jinja2 < 2.10.1 defined in requirements.txt.
requirements.txt update suggested: Jinja2 ~> 2.10.1.

**Comment by ryanolson** [comment]
Fixed on master in: 

https://github.com/NVIDIA/tensorrt-laboratory/commit/c67a0c1c384aecbb8af1eec531b0480bae9a3517
